# Generated by Django 2.1.1 on 2018-11-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOfficals',
            fields=[
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('id', models.IntegerField(default=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
